#!/usr/bin/env python3
"""Bundle the multi-file app into one self-contained Songbook.html.

Inlines style.css, chords.js, app.js, all bundled songbooks (as
window.__SONGBOOKS__) and all images (images/* as base64 data URIs). Chord
diagrams are drawn on the fly by chords.js, so no chord images are bundled.
The result reads no external files and works from file:// on desktop and
Android. The source multi-file app is untouched.
"""
import base64
import json
import os
import re
import sys

D = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(D, 'Songbook.html')

MIME = {
    '.png': 'image/png',
    '.gif': 'image/gif',
    '.jpg': 'image/jpeg',
    '.jpeg': 'image/jpeg',
    '.svg': 'image/svg+xml',
    '.webp': 'image/webp',
    '.ico': 'image/x-icon',
}


def read(rel):
    with open(os.path.join(D, rel), encoding='utf-8') as f:
        return f.read()


def data_uri(path):
    ext = os.path.splitext(path)[1].lower()
    mime = MIME.get(ext)
    if mime is None:
        raise SystemExit('unsupported image type: ' + path)
    with open(path, 'rb') as f:
        return 'data:' + mime + ';base64,' + base64.b64encode(f.read()).decode()


def load_songbooks():
    manifest = json.loads(read('songbooks/index.json'))
    out = []
    for entry in manifest.get('songbooks', []):
        sb = json.loads(read(os.path.join('songbooks', entry['file'])))
        out.append(sb)
    return out


html = read('index.html')
css = read('style.css')
chords = read('chords.js')
app = read('app.js')
songbooks = load_songbooks()

# 1) inline CSS
if '<link rel="stylesheet" href="style.css">' not in html:
    raise SystemExit('style.css <link> tag not found')
html = html.replace('<link rel="stylesheet" href="style.css">', '<style>\n' + css + '\n</style>')

# 2) drop the web-app manifest (file:// has no server to fetch it from)
html = html.replace('<link rel="manifest" href="manifest.webmanifest">', '')

# 3) inline all image-path attribute values (src/href/data-light/data-dark)
def inline_img(m):
    attr, val = m.group(1), m.group(2)
    if val.startswith('images/'):
        p = os.path.join(D, val)
        if not os.path.exists(p):
            raise SystemExit('missing image: ' + val)
        return attr + '="' + data_uri(p) + '"'
    return m.group(0)

html = re.sub(r'(src|href|data-light|data-dark)="([^"]+)"', inline_img, html)

# 4) inline the scripts; bundled songbooks become window.__SONGBOOKS__
songbooks_js = json.dumps(songbooks, ensure_ascii=False).replace('<', '\\u003c')
if '<script src="chords.js"></script>' not in html:
    raise SystemExit('chords.js <script> tag not found')
if '<script src="app.js"></script>' not in html:
    raise SystemExit('app.js <script> tag not found')
html = html.replace('<script src="chords.js"></script>', '<script>\n' + chords + '\n</script>')
html = html.replace(
    '<script src="app.js"></script>',
    '<script>window.__SONGBOOKS__ = ' + songbooks_js + ';</script>\n<script>\n' + app + '\n</script>')

# 5) self-containment sanity checks
bad = []
for pat in [r'src="chords/', r'src="images/', r'href="images/', r'data-light="images/', r'data-dark="images/',
            r'href="style\.css', r'src="chords\.js', r'src="app\.js', r'href="manifest\.webmanifest',
            r'href="sw\.js', r'https?://(?!www\.w3\.org)']:
    if re.search(pat, html):
        bad.append(pat)
if bad:
    raise SystemExit('bundle still references external resources: ' + ', '.join(bad))
for chunk, name in [(chords, 'chords.js'), (app, 'app.js'), (songbooks_js, 'songbooks')]:
    if '</script' in chunk.lower():
        raise SystemExit('inline content %s contains a closing script tag sequence' % name)
if '</style' in css.lower():
    raise SystemExit('inline style.css contains a closing style tag sequence')

banner = '<!-- Single-file build of Songbook; generated by build_single.py -->'
if html.lstrip().lower().startswith('<!doctype html>'):
    out = re.sub(r'^(\s*<!doctype html>)', r'\1\n' + banner, html, count=1, flags=re.IGNORECASE)
else:
    out = '<!doctype html>\n' + banner + '\n' + html

with open(OUT, 'w', encoding='utf-8') as f:
    f.write(out)

n_songs = sum(len(sb.get('songs', [])) for sb in songbooks)
print('wrote ' + OUT)
print('size: %.1f KB (%d songbooks, %d songs, chord diagrams generated on the fly)'
      % (len(out) / 1024.0, len(songbooks), n_songs))
